version: "3.8"

networks:
  docker-registry:
    name: docker-registry

services:
  registry:
    image: registry:${DOCKER_REGISTRY_VERSION}
    container_name: registry
    restart: unless-stopped
    ports:
      - "${DOCKER_REGISTRY_PORT}:${DOCKER_REGISTRY_PORT}"
    volumes:
      - ${DOCKER_REGISTRY_AUTH_PATH}:/auth
      - ${DOCKER_REGISTRY_VOLUME_STORAGE_PATH}:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    networks:
      - docker-registry

  registry-ui:
    image: joxit/docker-registry-ui:${DOCKER_REGISTRY_UI_VERSION}
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "${DOCKER_REGISTRY_UI_PORT}:80"
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: Docker Registry UI
      DELETE_IMAGES: true
      SHOW_CONTENT_DIGEST: true
      NGINX_PROXY_PASS_URL: http://registry:5000
      SHOW_CATALOG_NB_TAGS: true
      CATALOG_MIN_BRANCHES: 1
      CATALOG_MAX_BRANCHES: 1
      TAGLIST_PAGE_SIZE: 100
      REGISTRY_SECURED: false
      CATALOG_ELEMENTS_LIMIT: 1000
    depends_on:
      - registry
    networks:
      - docker-registry
    
