#!/bin/bash
# init.sh - PostgreSQL primary 초기화 스크립트 (환경변수 사용)
set -e

echo ">> initializing PostgreSQL primary server"

# psql 클라이언트 옵션
PSQL="psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER"

echo "  >> creating replication role: $POSTGRES_REPLICATION_USER"
$PSQL <<-EOSQL
  CREATE ROLE ${POSTGRES_REPLICATION_USER} WITH REPLICATION LOGIN PASSWORD '${POSTGRES_REPLICATION_PASSWORD}';
  SELECT pg_create_physical_replication_slot('$POSTGRES_REPLICATION_SLOT');
EOSQL
echo "  >> replication slot '$POSTGRES_REPLICATION_SLOT' created"

# 애플리케이션 사용자 및 스키마 생성
echo "  >> creating application users and schema"
$PSQL -d "$POSTGRES_DB" <<-EOSQL
  -- 스키마 생성
  CREATE SCHEMA IF NOT EXISTS $POSTGRES_DB;

  -- 애플리케이션 사용자 생성
  CREATE USER $EXAMPLE_NESTJS_POSTGRES_USER PASSWORD '$EXAMPLE_NESTJS_POSTGRES_PASSWORD';
  CREATE USER $EXAMPLE_SPRING_BOOT_POSTGRES_USER PASSWORD '$EXAMPLE_SPRING_BOOT_POSTGRES_PASSWORD';

  -- 데이터베이스 연결 권한
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $EXAMPLE_NESTJS_POSTGRES_USER;
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $EXAMPLE_SPRING_BOOT_POSTGRES_USER;

  -- 스키마 전체 권한 (CREATE, USAGE)
  GRANT ALL PRIVILEGES ON SCHEMA $POSTGRES_DB TO $EXAMPLE_NESTJS_POSTGRES_USER;
  GRANT ALL PRIVILEGES ON SCHEMA $POSTGRES_DB TO $EXAMPLE_SPRING_BOOT_POSTGRES_USER;

  -- 향후 생성될 테이블에 자동으로 권한 부여
  ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_DB GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $EXAMPLE_NESTJS_POSTGRES_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_DB GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $EXAMPLE_SPRING_BOOT_POSTGRES_USER;

  -- 시퀀스 권한 (AUTO_INCREMENT 등)
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $POSTGRES_DB TO $EXAMPLE_NESTJS_POSTGRES_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $POSTGRES_DB TO $EXAMPLE_SPRING_BOOT_POSTGRES_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_DB GRANT USAGE, SELECT ON SEQUENCES TO $EXAMPLE_NESTJS_POSTGRES_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_DB GRANT USAGE, SELECT ON SEQUENCES TO $EXAMPLE_SPRING_BOOT_POSTGRES_USER;
EOSQL

echo ">> PostgreSQL primary initialization completed"